spring:
  application:
    name: konumnot

  datasource:
    url: jdbc:postgresql://localhost:5432/apps
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
        format_sql: true
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect

  flyway:
    baseline-on-migrate: true

logging:
  level:
    root: INFO
    com.konumnot: DEBUG
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/konumnot.log

server:
  port: 8080
